config/routes.rb
Rails.application.routes.draw do
  get 'journal_articles/show'
  get 'members/show'
  get 'members/index'
  get 'country_references/index'
  get 'country_references/show'
  get 'pictures/index'
  get 'videos/index'
  get 'schools/index'
  get 'schools/show'
  get 'colleges/index'
  get 'colleges/show'
  get 'universities/index'
  get 'universities/show'
  get 'posts/index'
  get 'posts/show'
  get 'scholarships/index'
  get 'scholarships/show'
  get 'conferences/index'
  get 'conferences/show'
  get 'museums/index'
  get 'museums/show'
  devise_for :users

  ActiveAdmin.routes(self)
  namespace :admin do
    resources :countries do
      resources :museums
      resources :posts
      resources :scholarships
      resources :universities
    end
    resources :cities do
      resources :museums 
      resources :posts
      resources :universities
    end
    resources :universities do
      resources :scholarships
    end 
  end

  resources :countries do
    resources :museums
    resources :conferences
    resources :scholarships
    resources :posts
    resources :pictures
    resources :videos
    resources :country_references
    resources :universities do
      resources :colleges do
        resources :schools
      end
    end
    resources :cities do
      resources :sites
    end
  end

  resources :universities
  resources :colleges

  resources :cities

  resources :publishers
  resources :journals
  resources :books do
    collection do
      get :search
    end
  end
  resources :issues
  resources :journal_articles
  resources :academic_papers

  resources :subjects, param: :name
  resources :disciplines, param: :name
  resources :authors, param: :name
  resources :supervisor, param: :name
  resources :islamic_periods, param: :name

  get '/library', to: 'library#index'
  get '/library/browse', to: 'library#browse'
  get 'library/basic_search', to: 'library#basic_search'

  get '/about_us', :to => 'home#about_us'
  root 'home#index'
end

app/models/scholarship.rb
class Scholarship < ApplicationRecord
  include Filterable
  include Publishable

  user_owned
  
  belongs_to :university
  belongs_to :country
  belongs_to :category

  paginates_per 5

end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  breadcrumb "Countries", :countries_path
  def index
    @country = Country.find(params[:country_id])
    @scholarships = Scholarship.filter(params.slice(:country_id, :degree, :university, :category)).q_name(params[:q]).page(params[:page]).per(params[:results_per_page])
    breadcrumb @country.name, country_cities_path(@country)
    breadcrumb "Scholarships", country_scholarships_path(@country)
  end

  def show
    @i = Scholarship.find(params[:id])
    @country = Country.find(params[:country_id])
    breadcrumb @country.name, country_cities_path(@country)
    breadcrumb "Scholarships", country_scholarships_path(@country)
    breadcrumb @i.name, country_scholarship_path(@country, @i)
  end
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/scholarships/index.html.erb
<% title "Scholarships" %>
<h1 class="page-title">Scholarships in <%= @country.name %></h1>
<%= filters_and_order_for(country_scholarships_path(params[:country_id]), ["degree", "university", "category", "results_per_page"], params) %>
<div class="row">
    <% @scholarships.each do |i| %>
        <%= card_for(i.name, 
        {"Degree" => i.degree, 
        "University" => i.university.name, 
        "Scholarship" => i.scholarship,
        "Deadline" => i.deadline.strftime("%d/%m/%Y") },
        country_scholarship_path(@country, i), 3) %>
    <% end %>
</div>
<%= paginate @scholarships %>

app/views/scholarships/show.html.erb
<% title "#{@i.name}" %>
<div class="about">
    <h2><%= @i.name %>: </h2>
    <p><label>Degree:</label> <%= @i.degree %></p>
    <p><label>University:</label> <%= link_to  @i.university.name, university_path(@i.university) %></p>
    <p><label>Scholarship:</label> <%= @i.scholarship %></p>
    <p><label>Deadline:</label> <%= @i.deadline.strftime("%d/%m/%Y at %H:%M") %></p>
    <p class="lead "><%= @i.about.html_safe %></p>
</div>