config/routes.rb
Rails.application.routes.draw do
  get 'journal_articles/show'
  get 'members/show'
  get 'members/index'
  get 'country_references/index'
  get 'country_references/show'
  get 'pictures/index'
  get 'videos/index'
  get 'schools/index'
  get 'schools/show'
  get 'colleges/index'
  get 'colleges/show'
  get 'universities/index'
  get 'universities/show'
  get 'posts/index'
  get 'posts/show'
  get 'scholarships/index'
  get 'scholarships/show'
  get 'conferences/index'
  get 'conferences/show'
  get 'museums/index'
  get 'museums/show'
  devise_for :users

  ActiveAdmin.routes(self)
  namespace :admin do
    resources :countries do
      resources :museums
      resources :posts
      resources :scholarships
      resources :universities
    end
    resources :cities do
      resources :museums 
      resources :posts
      resources :universities
    end
    resources :universities do
      resources :scholarships
    end 
  end

  resources :countries do
    resources :museums
    resources :conferences
    resources :scholarships
    resources :posts
    resources :pictures
    resources :videos
    resources :country_references
    resources :universities do
      resources :colleges do
        resources :schools
      end
    end
    resources :cities do
      resources :sites
    end
  end

  resources :universities
  resources :colleges

  resources :cities

  resources :publishers
  resources :journals
  resources :books do
    collection do
      get :search
    end
  end
  resources :issues
  resources :journal_articles
  resources :academic_papers

  resources :subjects, param: :name
  resources :disciplines, param: :name
  resources :authors, param: :name
  resources :supervisor, param: :name
  resources :islamic_periods, param: :name

  get '/library', to: 'library#index'
  get '/library/browse', to: 'library#browse'
  get 'library/basic_search', to: 'library#basic_search'

  get '/about_us', :to => 'home#about_us'
  root 'home#index'
end

app/views/shared/_academic_paper_list_item.html.erb
<% if view == :detailed %>
    <a href="<%= academic_paper_path(p) %>"><h4><%= p.title %></h4></a>
    <p><label>Author(s): </label><%= safe_join(p.authors.map { |s| link_to  s.name, author_path(s.name) }, ", ").html_safe %> </p>
    <p><label>Paper Type: </label> <%= p.paper_type %> </p>
    <p><label>Publication Year: </label> <%= p.publication_year %> </p>
    <p><label>Subjects: </label> <%= safe_join(p.subjects.map { |s| link_to  s.name, subject_path(s.name) }, ", ").html_safe %> </p>
    <p><label>Keywords: </label> <%= p.keywords %> </p>
<% else %>

    <td><%= p.library_id %></td>
    <td><%= p.paper_type %></td>
    <td><%= safe_join(p.authors.map { |s| link_to  s.name, author_path(s.name) }, ", ").html_safe %></td>                        
    <td><a href="<%= academic_paper_path(p) %>"><%= p.title %></a></td>
    <td>N/A</td>
    <td><%= p.publication_year if p.publication_year %></td>
    <td><%= p.language if p.language %></td>

<% end %>

app/views/shared/_book_list_item.html.erb
<% if view == :detailed %>
    <a href="<%= book_path(b) %>"><h4><%= b.title %></h4></a>
    <p><label>Author(s): </label><%= safe_join(b.authors.map { |s| link_to  s.name, author_path(s.name) }, ", ").html_safe %> </p>
    <p><label>ISBN: </label> <%= b.isbn %> </p>
    <p><label>Subjects: </label> <%= safe_join(b.subjects.map { |s| link_to  s.name, subject_path(s.name) }, ", ").html_safe %> </p>
    <p><label>Keywords: </label> <%= b.keywords %> </p>
<% else %>
    <td><%= b.library_id %></td>
    <td><%= b.class.name %></td>
    <td> <%= safe_join(b.authors.map { |s| link_to  s.name, author_path(s.name) }, ", ").html_safe %></td>
    <td><a href="<%= book_path(b) %>"><%= b.title %></a></td>
    <td><a href="<%= publisher_path(b.publisher) if b.publisher %>"><%= b.publisher.name if b.publisher %></a></td>
    <td><%= b.year %></td>
    <td><%= b.language %></td>
<% end %>

app/views/shared/_detailed_view.html.erb
<div class="col s12 m9">
    <% if params[:q] == nil && search %>
        <h4>Please enter a search term.</h4>        
    <% elsif items.length > 0 && params[:q] != "" %>
        <% items.each do |r| %>
            <div class="row">
                <div class="col s12 m8">
                    <div class="content-type-name">
                        <span class="badge">
                            <%= "Book" if r.class == Book %>
                            <%= "Journal" if r.class == Journal %>
                            <%= "Academic Paper" if r.class == AcademicPaper %>
                            <%= "Journal Article" if r.class == JournalArticle %>
                        </span>
                    </div>
                    <%= render partial: "shared/journal_list_item", locals: {view: :detailed, j: r, arabic_title: params[:language] == "arabic"} if r.class == Journal %>
                    <%= render partial: "shared/book_list_item", locals: {view: :detailed, b: r} if r.class == Book %>
                    <%= render partial: "shared/academic_paper_list_item", locals: {view: :detailed, p: r} if r.class == AcademicPaper %>
                    <%= render partial: "shared/journal_article_list_item", locals: {view: :detailed, a: r} if r.class == JournalArticle %>
                </div>
                <div class="col s12 m4">
                    <% if r.class.name == "Book" || r.class.name == "Journal" %>
                        <% if r.cover.attached? %>
                            <%= image_tag  url_for(r.cover), style: "max-width: 150px; margin-bottom: 20px;" if r.cover.attached? %>
                        <% else %>
                            <%= image_tag  "no-thumb.jpg", style: "max-width: 150px; margin-bottom: 20px;" %>                                    
                        <% end %>
                    <% else %>
                        <%= image_tag  "no-thumb.jpg", style: "max-width: 150px; margin-bottom: 20px;" %>                                    
                    <% end %>
                </div>
            </div>
            <hr style="margin-bottom: 25px;">
        <% end %>
        <%= paginate items if paginate_items %>
    <% elsif params[:q] == "" %>
        <h4>Please enter a search term.</h4>
    <% elsif params[:q] != "" && items.length == 0 %>
        <h4>Sorry, but nothing matches your search.</h4>                    
    <% end %>        
</div>

app/views/shared/_documents_table.html.erb
<table class="highlight table table-striped sortable">
    <thead>
        <tr>
            <th><a href="#">ID</a></th>
            <th><a href="#">Type</a></th>
            <th><a href="#">Author(s)</a></th>
            <th><a href="#">Title</a></th>
            <th><a href="#">Publisher</a></th>
            <th><a href="#">Year</a></th>
            <th><a href="#">Language</a></th>
        </tr>
    </thead>
    <tbody>
    <% documents.each do |r| %>
        <tr>
            <%= render partial: "shared/journal_list_item", locals: {view: :simple, j: r} if r.class == Journal %>
            <%= render partial: "shared/book_list_item", locals: {view: :simple, b: r} if r.class == Book %>
            <%= render partial: "shared/academic_paper_list_item", locals: {view: :simple, p: r} if r.class == AcademicPaper %>
            <%= render partial: "shared/journal_article_list_item", locals: {view: :simple, a: r} if r.class == JournalArticle %>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/shared/_documents_view.html.erb
<% if model.try(:journal_articles) %>
    <a class="waves-effect waves-light btn <%= params[:document_type] == "journal_articles" ? "disabled" : "nothing" %>" href="?document_type=journal_articles">Journal Articles</a>
<% end %>
<% if model.try(:journals) %>
    <a class="waves-effect waves-light btn <%= params[:document_type] == "journals" ? "disabled" : "nothing" %>" href="?document_type=journals">Journals</a>
<% end %>
<% if model.try(:academic_papers) %>
    <a class="waves-effect waves-light btn <%= params[:document_type] == "academic_papers" ? "disabled" : "nothing" %>" href="?document_type=academic_papers">Academic Papers</a>
<% end %>
<% if model.try(:books) %>
    <a class="waves-effect waves-light btn <%= params[:document_type] == "books" ? "disabled" : "nothing" %>" href="?document_type=books">Books</a>
<% end %>


<div class="subjects-items-container">        
    <% if params[:document_type] == "books" %>
        <% if model.books %>
            <%= render partial: "shared/documents_table", locals: {documents: model.books} %>
        <% end %>
    <% elsif params[:document_type] == "journals" && model.class.name != "Author" %>
        <% if model.journals %>
            <%= render partial: "shared/documents_table", locals: {documents: model.journals} %>
        <% end %>
    <% elsif params[:document_type] == "academic_papers" && model.class.name != "Publisher" %>
        <% if model.academic_papers %>
            <%= render partial: "shared/documents_table", locals: {documents: model.academic_papers} %>
        <% end %>
    <% elsif params[:document_type] == "journal_articles" && model.class.name != "Publisher" %>
        <% if model.try(:journal_articles) %>
            <%= render partial: "shared/documents_table", locals: {documents: model.journal_articles} %>
        <% end %>
    <% end %>
</div>

app/views/shared/_download.html.erb
<div class="row">
    <h3 class="title"><%= defined?(text) ? text : "Gain Access" %></h3>
    <hr>
    <button type="button" class="btn-small" data-toggle="modal" data-target="#gain-access-modal">
            <%= defined?(text) ? text : "Gain Access" %>
    </button>
    <div class="modal fade" id="gain-access-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"><%= defined?(text) ? text : "Gain Access" %></h5>
                </div>
                <div class="modal-body">
                    <% if file.attachment %>
                        <%= link_to  "Download PDF", url_for(file), target: "_blank" %>
                    <% else %>
                        <p>Sorry, this file is not avalable at the moment.</p>
                    <% end %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_gain_access.html.erb
<div class="row">
    <h3 class="title">Gain Access</h3>
    <hr>
    <button type="button" class="btn-small" data-toggle="modal" data-target="#gain-access-modal">
            Gain Access
    </button>
    <div class="modal fade" id="gain-access-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Gain Access</h5>
                </div>
                <div class="modal-body">
                    <% if model.pdf.attachment %>
                        <%= link_to  "Download PDF", url_for(model.pdf), target: "_blank" %>
                    <% else %>
                        <p>Sorry, this file is not avalable at the moment.</p>
                    <% end %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_journal_article_list_item.html.erb
<% if view == :detailed %>
    <a href="<%= journal_article_path(a) %>"><h4><%= a.title %></h4></a>
    <p><label>Author(s): </label><%= safe_join(a.authors.map { |s| link_to  s.name, author_path(s.name) }, ", ").html_safe %></p>
    <% if a.issue.journal.subjects.length > 0 %><p><label>Subjects: </label> <%= safe_join(a.issue.journal.subjects.map { |s| link_to  s.name, subject_path(s.name) }, ", ").html_safe %> </p><% end %>
<% else %>
    <td>N/A</td>
    <td>Journal Article</td>
    <td><%= safe_join(a.authors.map { |s| link_to  s.name, author_path(s.name) }, ", ").html_safe %></td>
    <td><a href="<%= journal_article_path(a) %>"><%= a.title %></a></td>
    <td><a href="<%= publisher_path(a.issue.journal.publisher) if a.issue.journal.publisher %>"><%= a.issue.journal.publisher.name if a.issue.journal.publisher %></a></td>                        
    <td><%= "#{a.issue.journal.coverageFrom}-#{a.issue.journal.coverageTo}" if a.issue.journal.coverageFrom && a.issue.journal.coverageTo %></td>
    <td><%= a.issue.journal.language %> <%= "& #{a.issue.journal.second_language}" if !a.issue.journal.second_language.empty? %></td>
<% end %>

app/views/shared/_journal_list_item.html.erb
<% if view == :detailed %>
    <a href="<%= journal_path(j) %>"><h4><%= arabic_title ? j.arabic_title : j.title %></h4></a>
    <% if !j.isbn.empty? %><p><label>ISBN: </label> <%= j.isbn %> </p><% end %>
    <% if j.coverageFrom &&  j.coverageTo %><p><label>Coverage Years: </label> <%= "#{j.coverageFrom} - #{j.coverageTo}" %> </p><% end %>
    <% if j.subjects.length > 0 %><p><label>Subjects: </label> <%= safe_join(j.subjects.map { |s| link_to  s.name, subject_path(s.name) }, ", ").html_safe %> </p><% end %>
    <% if !j.keywords.empty? %><p><label>Keywords: </label> <%= j.keywords %> </p><% end %>    
<% else %>
    <td><%= j.library_id %></td>
    <td><%= j.class.name %></td>
    <td>N/A</td>
    <td><a href="<%= journal_path(j) %>"><%= j.title %></a></td>
    <td><a href="<%= publisher_path(j.publisher) if j.publisher %>"><%= j.publisher.name if j.publisher %></a></td>                        
    <td><%= "#{j.coverageFrom}-#{j.coverageTo}" if j.coverageFrom && j.coverageTo %></td>
    <td><%= j.language %> <%= "& #{j.second_language}" if !j.second_language.empty? %></td>
<% end %>

app/views/shared/_languages_select.html.erb
<select data-placeholder="Choose a Language..." name="language" onChange="this.form.submit()">
  <option></option>
  <option value="Afrikanns">Afrikanns</option>
  <option value="Albanian">Albanian</option>
  <option value="Arabic">Arabic</option>
  <option value="Armenian">Armenian</option>
  <option value="Basque">Basque</option>
  <option value="Bengali">Bengali</option>
  <option value="Bulgarian">Bulgarian</option>
  <option value="Catalan">Catalan</option>
  <option value="Cambodian">Cambodian</option>
  <option value="Chinese (Mandarin)">Chinese (Mandarin)</option>
  <option value="Croation">Croation</option>
  <option value="Czech">Czech</option>
  <option value="Danish">Danish</option>
  <option value="Dutch">Dutch</option>
  <option value="English">English</option>
  <option value="Estonian">Estonian</option>
  <option value="Fiji">Fiji</option>
  <option value="Finnish">Finnish</option>
  <option value="French">French</option>
  <option value="Georgian">Georgian</option>
  <option value="German">German</option>
  <option value="Greek">Greek</option>
  <option value="Gujarati">Gujarati</option>
  <option value="Hebrew">Hebrew</option>
  <option value="Hindi">Hindi</option>
  <option value="Hungarian">Hungarian</option>
  <option value="Icelandic">Icelandic</option>
  <option value="Indonesian">Indonesian</option>
  <option value="Irish">Irish</option>
  <option value="Italian">Italian</option>
  <option value="Japanese">Japanese</option>
  <option value="Javanese">Javanese</option>
  <option value="Korean">Korean</option>
  <option value="Latin">Latin</option>
  <option value="Latvian">Latvian</option>
  <option value="Lithuanian">Lithuanian</option>
  <option value="Macedonian">Macedonian</option>
  <option value="Malay">Malay</option>
  <option value="Malayalam">Malayalam</option>
  <option value="Maltese">Maltese</option>
  <option value="Maori">Maori</option>
  <option value="Marathi">Marathi</option>
  <option value="Mongolian">Mongolian</option>
  <option value="Nepali">Nepali</option>
  <option value="Norwegian">Norwegian</option>
  <option value="Persian">Persian</option>
  <option value="Polish">Polish</option>
  <option value="Portuguese">Portuguese</option>
  <option value="Punjabi">Punjabi</option>
  <option value="Quechua">Quechua</option>
  <option value="Romanian">Romanian</option>
  <option value="Russian">Russian</option>
  <option value="Samoan">Samoan</option>
  <option value="Serbian">Serbian</option>
  <option value="Slovak">Slovak</option>
  <option value="Slovenian">Slovenian</option>
  <option value="Spanish">Spanish</option>
  <option value="Swahili">Swahili</option>
  <option value="Swedish ">Swedish </option>
  <option value="Tamil">Tamil</option>
  <option value="Tatar">Tatar</option>
  <option value="Telugu">Telugu</option>
  <option value="Thai">Thai</option>
  <option value="Tibetan">Tibetan</option>
  <option value="Tonga">Tonga</option>
  <option value="Turkish">Turkish</option>
  <option value="Ukranian">Ukranian</option>
  <option value="Urdu">Urdu</option>
  <option value="Uzbek">Uzbek</option>
  <option value="Vietnamese">Vietnamese</option>
  <option value="Welsh">Welsh</option>
  <option value="Xhosa">Xhosa</option>
</select>

<script>
    $("select option[value='<%= params[:language] %>']").attr("selected","selected");
</script>

app/views/shared/_letter_grouped_list.html.erb
<h1>Browse by <% model.class.name.humanize %></h1>
<div class="letters-container">
    <ul class="pagination">
        <% [*('A'..'Z')].each do |l| %>
            <li class="page-item"><a class="page-link" href="#<%= l %>"><%= l %></a></li>
        <% end %>
    </ul>
</div>
<div class="subjects-container">
    <% model.each do |letter, group| %>
        <h3 id="<%= letter %>"><%= letter %></h3>
        <ul>
            <% group.each do |element|%>
                <% if element.class.name == "Author" %>
                    <li><%= link_to  element.name.capitalize, author_path(element.name) %></li>
                <% end %>
                <% if element.class.name == "Publisher" %>
                    <li><%= link_to  element.name.capitalize, publisher_path(element.id) %></li>
                <% end %>
            <% end %>
        </ul>
    <% end %>
</div>
<script>
    $('.pagination li').click(function() {
        $('.page-item').removeClass("active");
        $(this).toggleClass("active");
    });
</script>

app/views/shared/_navigation.html.erb
<div class="history-nav">
    <% nav.each do |n| %>
        <%= link_to n[:title], n[:url] %>
    <% end %>
    <%= link_to yield(:title), request.path, :class => 'no-link' %>
</div>

app/views/shared/_simple_view.html.erb
<div class="col s12 m9">
    <% if params[:q] == nil %>
        <h4>Please enter a search term.</h4>        
    <% elsif items.length > 0 && params[:q] != "" %>
        <%= render partial: "shared/documents_table", locals: {documents: items} %>        
        <%= paginate items %>
    <% elsif params[:q] == "" %>
        <h4>Please enter a search term.</h4>
    <% elsif params[:q] != "" && items.length == 0 %>
        <h4>Sorry, but nothing matches your search.</h4>                    
    <% end %>        
</div>